"""Family definitions: which glyph packs, styles, axes and metrics each
distributed family gets.

Glyph modules register glyphs with `pack=` ('core' = Latin/Greek/Cyrillic +
symbols, 'arabic', 'hangul', 'han', ...) and `families=` naming the
*styles* ('sans', 'mono') they support.  A family includes a glyph when its
style is in gd.families and gd.pack is in the family's packs.
"""
from __future__ import annotations

from dataclasses import dataclass, field

LATIN_METRICS = dict(asc=960, desc=-240, gap=0, win_asc=1050, win_desc=330)
ARABIC_METRICS = dict(asc=1060, desc=-440, gap=0, win_asc=1200, win_desc=560)
CJK_METRICS = dict(asc=1000, desc=-300, gap=0, win_asc=1100, win_desc=360)
HEBREW_METRICS = dict(asc=980, desc=-560, gap=0, win_asc=1100, win_desc=800)   # stacked niqqud at Black


@dataclass
class Family:
    id: str
    name: str
    ps: str
    style: str                 # 'sans' or 'mono' (skeleton style)
    packs: tuple
    italic: bool = True
    kern: bool = True
    metrics: dict = field(default_factory=lambda: dict(LATIN_METRICS))
    langs: tuple = ()          # OpenType language tags of interest (informational)


FAMILIES = {
    "sans": Family("sans", "Bloxwap Sans", "BloxwapSans", "sans", ("core",)),
    "mono": Family("mono", "Bloxwap Mono", "BloxwapMono", "mono", ("core",), kern=False),
    "sans-arabic": Family("sans-arabic", "Bloxwap Sans Arabic", "BloxwapSansArabic", "sans",
                          ("core", "arabic"), italic=False, metrics=dict(ARABIC_METRICS)),
    "mono-arabic": Family("mono-arabic", "Bloxwap Mono Arabic", "BloxwapMonoArabic", "mono",
                          ("core", "arabic"), italic=False, kern=False, metrics=dict(ARABIC_METRICS)),
    "sans-kr": Family("sans-kr", "Bloxwap Sans KR", "BloxwapSansKR", "sans",
                      ("core", "cjk", "hangul"), italic=False, metrics=dict(CJK_METRICS)),
    "mono-kr": Family("mono-kr", "Bloxwap Mono KR", "BloxwapMonoKR", "mono",
                      ("core", "cjk", "hangul"), italic=False, kern=False, metrics=dict(CJK_METRICS)),
    "sans-sc": Family("sans-sc", "Bloxwap Sans SC", "BloxwapSansSC", "sans",
                      ("core", "cjk", "han"), italic=False, metrics=dict(CJK_METRICS)),
    "mono-sc": Family("mono-sc", "Bloxwap Mono SC", "BloxwapMonoSC", "mono",
                      ("core", "cjk", "han"), italic=False, kern=False, metrics=dict(CJK_METRICS)),
    "sans-jp": Family("sans-jp", "Bloxwap Sans JP", "BloxwapSansJP", "sans",
                      ("core", "cjk", "kana", "han-jp"), italic=False, metrics=dict(CJK_METRICS)),
    "mono-jp": Family("mono-jp", "Bloxwap Mono JP", "BloxwapMonoJP", "mono",
                      ("core", "cjk", "kana", "han-jp"), italic=False, kern=False, metrics=dict(CJK_METRICS)),
    "sans-hebrew": Family("sans-hebrew", "Bloxwap Sans Hebrew", "BloxwapSansHebrew", "sans",
                          ("core", "hebrew"), italic=False, metrics=dict(HEBREW_METRICS)),
    "mono-hebrew": Family("mono-hebrew", "Bloxwap Mono Hebrew", "BloxwapMonoHebrew", "mono",
                          ("core", "hebrew"), italic=False, kern=False, metrics=dict(HEBREW_METRICS)),
    "sans-armenian": Family("sans-armenian", "Bloxwap Sans Armenian", "BloxwapSansArmenian", "sans",
                            ("core", "armenian")),
    "mono-armenian": Family("mono-armenian", "Bloxwap Mono Armenian", "BloxwapMonoArmenian", "mono",
                            ("core", "armenian"), kern=False),
    "sans-georgian": Family("sans-georgian", "Bloxwap Sans Georgian", "BloxwapSansGeorgian", "sans",
                            ("core", "georgian")),
    "mono-georgian": Family("mono-georgian", "Bloxwap Mono Georgian", "BloxwapMonoGeorgian", "mono",
                            ("core", "georgian"), kern=False),
    # pixel is generated by bwfont.pixel; listed for naming / packaging
    "pixel": Family("pixel", "Bloxwap Pixel", "BloxwapPixel", "pixel", ("core",), kern=False),
}


def get(fid: str) -> Family:
    return FAMILIES[fid]
