// GENERATED by tools/webfonts.py (run by tools/postprocess.py). Do not edit by hand.
// A content hash of apps/docs/public/fonts/**/*.woff2, appended to font and stylesheet URLs
// so browsers never keep stale fonts (or a cached 404) after a release.
export const FONT_VERSION = '388e7417ad';
